spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tmall_springboot?characterEncoding=UTF-8
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

server:
  context-path: /tmall_springboot

swagger:
  enabled: true